# Generated by Django 4.2.1 on 2023-05-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('reference_key', models.CharField(max_length=8, unique=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('employee_name', models.CharField(max_length=100)),
            ],
        ),
    ]
