# Generated by Django 4.2.1 on 2023-05-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadeddata',
            old_name='employee_name',
            new_name='employee_first_name',
        ),
        migrations.RenameField(
            model_name='uploadeddata',
            old_name='reference_key',
            new_name='reference_id',
        ),
        migrations.RemoveField(
            model_name='uploadeddata',
            name='upload_date',
        ),
    ]
